name: octattoo_app
description: "Mobile, tablet & desktop app for tattoo artists to gain organization, productivity and quality on a daily basis to devote more time to tattooing and creation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.2.3
  intl: any
  logger: ^2.4.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env